### ISSUE TITLE
Props created via DI cannot be passed between nodes.

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/Akka.DI.AutoFac#14]
This is something, I've detected when trying to use DI-ed `Props` in combination with cluster routers. Effect:

```
[23:35:06 ERR] AssociationError [akka.tcp://Lighthouse@127.0.0.1:34161] <- akka.tcp://Lighthouse@127.0.0.1:34163: Error [Value cannot be null.
Parameter name: system] [   at Akka.DI.AutoFac.AutoFacDependencyResolver..ctor(ILifetimeScope container, ActorSystem system)
   at Void .ctor(Autofac.ILifetimeScope, Akka.Actor.ActorSystem)(Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.DaemonMsgCreateSerializer.PropsFromProto(PropsData protoProps)
   at Akka.Remote.Serialization.DaemonMsgCreateSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.MessageSerializer.Deserialize(ActorSystem system, Payload messageProtocol)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_1(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
```

I think, there's a hole in DI specs. This may be pretty bold statement, but `Props` serialization/deserialization is crucial part of Akka.NET and if some Props cannot be send over the wire, then they should not be called as such.

I think the reason likes in Akka.DI.Core ActorProducer which refers for `IDependencyResolver` and is serialized as part of the Props for some reason.  If I'm right this problem may not be unique to Autofac, but actually it affects all DI plugins.

Quite possible that surrogates on either `DIActorProducer` or `IDependencyResolver` level could help here.

**Comment by Danthar** [comment]
We have ran into this problem before. And afaik it is well known (at least among us core devs) that DI'ed props are not usable across the wire. (remember?)
We even marked the DI implementation for each plugin with `INoSerializationVerificationNeeded` to prevent exceptions from occuring. But the root cause, the fact that it attempts to serialize the DI container itself. Still needs to be resolved. Fixing that would go a long way towards making DI'ed props usable across the wire.

**Comment by andreyleskov** [comment]
Hey, any updates on this? Just ran into the same issue.

**Comment by Danthar** [comment]
Nope.

**Comment by andreyleskov** [comment]
Ok, thanks for the notice! 
Did a workaround with wrapping actor with dependencies in a dependent-less "cells" creating the original actor inside via Context.System.DI() and forwarding all messages to it.

**Comment by Lex45x** [comment]
Akka.Net makes me angry due to such kind of issues.
